const $=id=>document.getElementById(id);
let stream=null,photo=null,originalImage=null,dragStart=null,boxes=[],cropUrls=[];
async function startCamera(){try{if(!navigator.mediaDevices?.getUserMedia)throw Error();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});$("video").srcObject=stream;$("video").style.display="block";$("preview").style.display="none";$("cameraHint").style.display="none";$("takePhoto").disabled=false;}catch(e){alert("カメラを起動できませんでした。「写真を選ぶ」を使ってください。");}}
$("startCamera").addEventListener("click",startCamera);
$("takePhoto").addEventListener("click",()=>{const v=$("video"),c=$("canvas");if(!v.videoWidth)return alert("カメラ映像を準備中です。");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0);setPhoto(c.toDataURL("image/jpeg",.92));if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}});
$("fileInput").addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setPhoto(r.result);r.readAsDataURL(f);});
function loadImage(src){return new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=src;});}
function setPhoto(src){photo=src;boxes=[];cropUrls=[];$("preview").src=src;$("preview").style.display="block";$("video").style.display="none";$("cameraHint").style.display="none";$("selectionHelp").hidden=false;$("cropStage").hidden=false;loadImage(src).then(i=>{originalImage=i;drawStage();});}
function drawStage(){if(!originalImage)return;const c=$("selectionCanvas"),max=Math.min($("cropStage").clientWidth||620,680),s=Math.min(1,max/originalImage.naturalWidth);c.width=Math.round(originalImage.naturalWidth*s);c.height=Math.round(originalImage.naturalHeight*s);const x=c.getContext("2d");x.drawImage(originalImage,0,0,c.width,c.height);boxes.forEach((b,i)=>{x.strokeStyle="#ff7b22";x.lineWidth=3;x.strokeRect(b.x*c.width,b.y*c.height,b.w*c.width,b.h*c.height);x.fillStyle="#ff7b22";x.fillRect(b.x*c.width,b.y*c.height,24,24);x.fillStyle="#fff";x.font="bold 15px sans-serif";x.fillText(String(i+1),b.x*c.width+7,b.y*c.height+17);});$("analyze").textContent="選んだ商品で検索結果を作成 ("+boxes.length+"/3)";$("analyze").disabled=!boxes.length;}
const cv=$("selectionCanvas");
cv.addEventListener("pointerdown",e=>{if(!originalImage||boxes.length>=3)return;const r=cv.getBoundingClientRect();dragStart={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};cv.setPointerCapture(e.pointerId);});
cv.addEventListener("pointerup",e=>{if(!dragStart)return;const r=cv.getBoundingClientRect(),p={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height},a=dragStart;dragStart=null;const b={x:Math.max(0,Math.min(a.x,p.x)),y:Math.max(0,Math.min(a.y,p.y)),w:Math.abs(p.x-a.x),h:Math.abs(p.y-a.y)};if(b.w<.025||b.h<.025)return;boxes.push(b);drawStage();});
$("clearBoxes").addEventListener("click",()=>{boxes=[];drawStage();});
$("analyze").addEventListener("click",()=>{if(!originalImage)return;cropUrls=boxes.map(b=>{const x=Math.round(b.x*originalImage.naturalWidth),y=Math.round(b.y*originalImage.naturalHeight),w=Math.max(1,Math.round(b.w*originalImage.naturalWidth)),h=Math.max(1,Math.round(b.h*originalImage.naturalHeight)),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(originalImage,x,y,w,h,0,0,w,h);return c.toDataURL("image/jpeg",.94);});$("resultList").innerHTML=cropUrls.map((url,i)=>'<article class="item"><div class="number">'+(i+1)+'</div><img class="thumb crop" src="'+url+'" alt="切り抜いた商品"><div><h3>商品 '+(i+1)+'</h3><p>この商品の画像をGoogleレンズで検索します。</p><button type="button" class="primary" data-open="'+i+'">切り抜き画像を開く・保存</button><a class="source" target="_blank" rel="noopener" href="https://lens.google.com/">Googleレンズを開く ↗</a><p class="muted">画像を開いて長押しし「写真に保存」→ Googleレンズで保存した画像を選んでください。</p></div></article>').join("");$("home").hidden=true;$("results").hidden=false;$("selectionHelp").hidden=true;$("cropStage").hidden=true;window.scrollTo(0,0);document.querySelectorAll("[data-open]").forEach(b=>b.addEventListener("click",()=>{const w=window.open();if(!w){alert("ポップアップを許可してください。");return;}w.document.write('<meta name="viewport" content="width=device-width,initial-scale=1"><p>画像を長押しして「写真に保存」を選んでください。</p><img style="width:100%;height:auto" src="'+cropUrls[Number(b.dataset.open)]+'">');w.document.close();}));});
$("newSearch").addEventListener("click",()=>{photo=null;originalImage=null;boxes=[];cropUrls=[];$("preview").style.display="none";$("video").style.display="block";$("analyze").disabled=true;$("fileInput").value="";$("results").hidden=true;$("home").hidden=false;$("selectionHelp").hidden=true;$("cropStage").hidden=true;});
$("back").addEventListener("click",()=>{$("detail").hidden=true;$("home").hidden=false;});
