const $=id=>document.getElementById(id);
let stream=null,photo=null;
async function startCamera(){try{if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error("camera");stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});const v=$("video");v.srcObject=stream;v.style.display="block";$("preview").style.display="none";$("cameraHint").style.display="none";$("takePhoto").disabled=false}catch(e){alert("カメラを起動できませんでした。許可済みなら「写真を選ぶ」を使えます。");}}
$("startCamera").addEventListener("click",startCamera);
$("takePhoto").addEventListener("click",()=>{const v=$("video"),c=$("canvas");if(!v.videoWidth){alert("カメラの映像がまだ準備できていません。");return}c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0);setPhoto(c.toDataURL("image/jpeg",.82));if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}});
$("fileInput").addEventListener("change",e=>{const f=e.target.files&&e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>setPhoto(r.result);r.readAsDataURL(f)});
function setPhoto(src){photo=src;$("preview").src=src;$("preview").style.display="block";$("video").style.display="none";$("cameraHint").style.display="none";$("analyze").disabled=false}
$("analyze").addEventListener("click",async()=>{if(!photo)return;show("results");$("resultList").innerHTML='<div class="loading"><b>AI解析中です…</b><br><br>商品1個だけを解析します。</div>';try{const text=await askVision(await resizeImage(photo,1100,.72)),item=parseOne(text);if(!item)throw new Error("AIは返答しましたが商品情報を読み取れませんでした。");const crop=makeCrop(photo,item.box);$("resultList").innerHTML='<article class="item"><div class="number">1</div>'+(crop?'<img class="thumb crop" src="'+crop+'" alt="AIが認識した商品">':'<div class="thumb"></div>')+'<div><h3>'+escapeHtml(item.name)+'</h3>'+(item.brand!=="不明"?'<p><b>メーカー：</b>'+escapeHtml(item.brand)+'</p>':'')+(item.model!=="不明"?'<p><b>型番・シリーズ：</b>'+escapeHtml(item.model)+'</p>':'')+'<p><b>AI確度：</b>'+Math.round(item.confidence*100)+'%</p><p class="muted">'+escapeHtml(item.reason)+'</p></div></article>'}catch(e){console.error(e);$("resultList").innerHTML='<div class="loading"><b>AI解析できませんでした。</b><br><br>'+escapeHtml(e.message||String(e))+'</div>'}});
async function askVision(dataUrl){const mod=await import("https://cdn.jsdelivr.net/npm/@gradio/client/dist/index.min.js"),Client=mod.Client,handle_file=mod.handle_file;let app;try{app=await Client.connect("developer0hye/Qwen2.5-VL-7B-Instruct")}catch(e){throw new Error("AIサービスに接続できません: "+(e.message||e))}try{const file=handle_file(dataUrlToBlob(dataUrl));const prompt='この画像の商品を1個だけ識別してください。棚・背景・値札・人は無視。商品名、メーカー/ブランド、型番/シリーズ、理由、確度、商品の位置boxをJSONだけで返してください。boxは画像全体を1000x1000としたx,y,w,h。分からない情報は不明。必ず次の形式: {"name":"商品名","brand":"不明","model":"不明","confidence":0.8,"reason":"理由","box":{"x":100,"y":100,"w":300,"h":300}}';const result=await app.predict("/qwen_vl_inference",[file,prompt]);if(!result||!result.data)throw new Error("AIから空の結果が返りました。");return Array.isArray(result.data)?String(result.data[0]||""):String(result.data)}catch(e){console.error("AI ERROR",e);throw new Error("AI解析処理でエラーが発生しました: "+(e.message||String(e)))}}
function parseOne(text){const m=String(text).match(/\{[\s\S]*\}/);if(!m)return null;try{const x=JSON.parse(m[0]);if(!x||!x.name)return null;return{name:String(x.name),brand:String(x.brand||"不明"),model:String(x.model||"不明"),confidence:Math.max(0,Math.min(1,Number(x.confidence)||0)),reason:String(x.reason||""),box:{x:Number(x.box?.x)||0,y:Number(x.box?.y)||0,w:Number(x.box?.w)||0,h:Number(x.box?.h)||0}}}catch(e){return null}}
function dataUrlToBlob(s){const p=s.split(","),mime=(p[0].match(/data:([^;]+)/)||[])[1]||"image/jpeg",b=atob(p[1]),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return new Blob([a],{type:mime})}
async function resizeImage(src,max,q){const img=new Image();img.src=src;await new Promise((r,j)=>{img.onload=r;img.onerror=j});const sc=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement("canvas");c.width=Math.round(img.naturalWidth*sc);c.height=Math.round(img.naturalHeight*sc);c.getContext("2d").drawImage(img,0,0,c.width,c.height);return c.toDataURL("image/jpeg",q)}
$("newSearch").addEventListener("click",()=>{photo=null;$("preview").style.display="none";$("video").style.display="block";$("analyze").disabled=true;show("home")});
$("back").addEventListener("click",()=>show("home"));
function show(id){["home","results","detail"].forEach(x=>$(x).hidden=x!==id);window.scrollTo(0,0)}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function makeCrop(src,box){if(!src||!box||box.w<5||box.h<5)return "";const img=$("preview");if(!img.naturalWidth||!img.naturalHeight)return "";const sx=Math.max(0,Math.round(box.x/1000*img.naturalWidth)),sy=Math.max(0,Math.round(box.y/1000*img.naturalHeight)),sw=Math.min(img.naturalWidth-sx,Math.round(box.w/1000*img.naturalWidth)),sh=Math.min(img.naturalHeight-sy,Math.round(box.h/1000*img.naturalHeight));if(sw<5||sh<5)return "";const c=document.createElement("canvas"),scale=Math.min(1,500/Math.max(sw,sh));c.width=Math.max(80,Math.round(sw*scale));c.height=Math.max(80,Math.round(sh*scale));c.getContext("2d").drawImage(img,sx,sy,sw,sh,0,0,c.width,c.height);return c.toDataURL("image/jpeg",.85)}